name: surf_shelf
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.19.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.5.3
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
